# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            R and Blues
tagline:          'A data science blog'
description:      'Falhando em rejeitar a hipótese nula quando ela é falsa!'
url:              http://blog.randblues.pro/
baseurl:          /

author:
  name:           'Adelmo Filho'
  url:            http://blog.randblues.pro/

paginate:         5

# Custom vars
version:          1.0.0 "Getting started"

github:           
  repo:           https://github.com/adelmofilho
  
# Gems
gems: [jekyll-paginate]
