# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Variável Aleatória
tagline:          'A data science blog'
description:      'Falhando em rejeitar a hipótese nula quando ela é falsa!'
url:              https://adelmofilho.github.io/
baseurl:          /

author:
  name:           'Adelmo Filho'
  url:            https://adelmofilho.github.io/

paginate:         5

# Custom vars
version:          1.0.0 "Getting started"

github:           
  repo:           https://github.com/adelmofilho
  
# Gems
gems: [jekyll-paginate]