# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Variável Aleatória
tagline:          'A Jekyll theme'
description:      'Falhando em rejeitar a hipótese nula quando ela é falsa!'
url:              https://adelmofilho.github.io/
baseurl:          /

author:
  name:           'Adelmo Filho'
  url:            https://twitter.com/SoulFilho

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           adelmofilho.github.io
  
# Gems
gems: [jekyll-paginate]